version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fullstack_api
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - fullstack_network
    entrypoint: /bin/bash -c "echo 'Waiting for database to be ready...' && sleep 30 && dotnet FullStackCodingChallenge.dll"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fullstack_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "X9#pQw$4Zt!"
      ACCEPT_EULA: "Y"
    networks:
      - fullstack_network
    volumes:
      - sql_data:/var/opt/mssql
    command: /opt/mssql/bin/sqlservr

networks:
  fullstack_network:

volumes:
  sql_data:
